"""empty message

Revision ID: 2e13db0c28f7
Revises: 
Create Date: 2023-05-14 17:08:07.756617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e13db0c28f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eng_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng_word', sa.String(length=40), nullable=False),
    sa.Column('ts', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng_word')
    )
    op.create_table('parts_of_speech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pos')
    )
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_psw', sa.String(length=255), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('example', sa.String(length=40), nullable=False),
    sa.Column('id_pos', sa.Integer(), nullable=False),
    sa.Column('id_eng_word', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_eng_word'], ['eng_words.id'], ),
    sa.ForeignKeyConstraint(['id_pos'], ['parts_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts_eng_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_text', sa.Integer(), nullable=True),
    sa.Column('id_eng_word', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_eng_word'], ['eng_words.id'], ),
    sa.ForeignKeyConstraint(['id_text'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tr_rus_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rus_word', sa.String(length=40), nullable=False),
    sa.Column('id_pos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pos'], ['parts_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rus_word')
    )
    op.create_table('eng_rus_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rus_word', sa.Integer(), nullable=True),
    sa.Column('id_eng_word', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_eng_word'], ['eng_words.id'], ),
    sa.ForeignKeyConstraint(['id_rus_word'], ['tr_rus_word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eng_rus_words')
    op.drop_table('tr_rus_word')
    op.drop_table('texts_eng_words')
    op.drop_table('examples')
    op.drop_table('user')
    op.drop_table('texts')
    op.drop_table('parts_of_speech')
    op.drop_table('eng_words')
    # ### end Alembic commands ###
