"""empty message

Revision ID: b5a5c0dd86ab
Revises: 2e13db0c28f7
Create Date: 2023-05-14 17:43:29.616667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a5c0dd86ab'
down_revision = '2e13db0c28f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eng_words', schema=None) as batch_op:
        batch_op.alter_column('eng_word',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('ts',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.alter_column('example',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('parts_of_speech', schema=None) as batch_op:
        batch_op.alter_column('pos',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('tr_rus_word', schema=None) as batch_op:
        batch_op.alter_column('rus_word',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tr_rus_word', schema=None) as batch_op:
        batch_op.alter_column('rus_word',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('parts_of_speech', schema=None) as batch_op:
        batch_op.alter_column('pos',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.alter_column('example',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('eng_words', schema=None) as batch_op:
        batch_op.alter_column('ts',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('eng_word',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
